### ISSUE TITLE
Long strings

### ISSUE THREAD

**Issue by mradzinski** [jobandtalent/AnimatedTextInput#10]
**Steps to reproduce the issue:**
1. Start by typing a long string into a `type = .standard` field till the text can't fit anymore into it.
2. _Issue 1:_ The field does not scroll horizontally nor reduces it's font size, and because of this newly entered characters become invisible to the user.
3. Now press the left arrow key
4. _Issue 2:_ The part of the long string that was invisible now is visible when it should've been always visible to the user.

**Expected result:**
1. The font should be reduced to accommodate long strings or there should be some sort of horizontal scroll while the user is typing to keep showing the newly entered characters.
2. Pressing the right and left arrow keys on my keyboard should allow me to move freely inside the field.

**Comment by victorBaro** [comment]
Thank you @mradzinski for reporting. Will update soon.

**Comment by victorBaro** [comment]
Hello @mradzinski 
I have just taken a look at your issue and I can't reproduce. The behaviour is correct. 

![](http://g.recordit.co/ajFsXp1Azs.gif)

This gif is extracted from the example app. I encourage you to open it and check its usage.

---

In addition, if you want to add any other behaviour (like reducing the font), I suggest you create your own subclass of UITextField/UITextView, and use:

``` swift
let myTextView = MyTextView()
animatedTextInput.configure(with type: .generic(myTextView))
```

This will add your own implementation of UITextField/UITextView as a subview. Another suggestion is that you extend `AnimatedTextInputType` and create your own `AnimatedTextInputConfigurator.
