### ISSUE TITLE
How can i limit height for multiline

### ISSUE THREAD

**Issue by thang-nm** [jobandtalent/AnimatedTextInput#105]
I want to set max height for input. If content over max height, it shows scroll.
How i can do that? Thanks!

**Comment by victorBaro** [comment]
Good question. It is currently not supported but it would be a really nice addition if you have the time to submit a pull request.
The component internally uses a UITextView so it should be possible to specify a maximum height.

**Comment by bystritskiy** [comment]
This is a very big problem! :(

**Comment by victorBaro** [comment]
Have you guys tried to use autolayout for achieving this? Set a height constraint lower than or equal to some value.
I will try to take a look at this and see if I can manage to do it.

**Comment by Tantalum73** [comment]
Hi ✌🏼
Please take a look at #112. My PR addresses your issue :]
