### ISSUE TITLE
'weak' should not be applied to a property declaration in a protocol and will be disallowed in future versions

### ISSUE THREAD

**Issue by seanpavlak** [jobandtalent/AnimatedTextInput#107]
AnimatedTextInput.swift

**Line 572:**    weak var textInputDelegate: TextInputDelegate? { get set }
results in a swift compiler warning

**Comment by Tantalum73** [comment]
I think your issue was resolved during the Merge of PR #109 by @Anarchoschnitzel ✌🏼
