### ISSUE TITLE
How can resize the line length?

### ISSUE THREAD

**Issue by Premal-Khetani** [jobandtalent/AnimatedTextInput#11]
I want to give margin from right side. Its touched to the end right now. 

How can i give the Margin from right side so i can make design more better as per Mock ?

**Comment by victorBaro** [comment]
Hello @Premal-Khetani 
You can define your own styles by creating a new struct that conforms to `AnimatedTextInputStyle`. In the example there is 1 style provided, `AnimatedTextInputStyleBlue`.

``` swift
public struct AnimatedTextInputStyleBlue: AnimatedTextInputStyle {

    public let activeColor = ColorPalette.primaryBlue.base
    public let inactiveColor = ColorPalette.dark.alpha60
    public let errorColor = ColorPalette.red.base
    public let textInputFont = FontBook.body1
    public let textInputFontColor = ColorPalette.dark.base
    public let placeholderMinFontSize: CGFloat = 13
    public let counterLabelFont: UIFont? = FontBook.footNote
    public let leftMargin: CGFloat = 16
    public let topMargin: CGFloat = 24
    public let rightMargin: CGFloat = 0
    public let bottomMargin: CGFloat = 16
    public let yHintPositionOffset: CGFloat = 8

    public init() { }
}
```

The `rightMargin` is set to 0. 

Just, be aware that changing this value will apply a right margin to all components inside the view, not just the line. If you to apply a margin just to the line, I recommend you to fork this project and extend `AnimatedTextInputStyle`. Add a new property for the lineRightMargin and modify the following line accordingly:

``` swift
    // Search for this line in AnimatedTextInput.swift and modify the constant
    pinTrailing(toTrailingOf: lineView, constant: style.rightMargin)
```

**Comment by Premal-Khetani** [comment]
@victorBaro  Thanks Thanks for the help :)
