### ISSUE TITLE
Secured Entry

### ISSUE THREAD

**Issue by cesarmtz93** [jobandtalent/AnimatedTextInput#117]
is there a way in that I can set the entry secure for any type of field? e.g. numeric I want it to be secured

**Comment by victorBaro** [comment]
Not with the current implementation. But you can create your own `Configurator`.
You need to create your own `TextInput` and configure the component with the generic type
Something like this:

```swift
let customInput = AnimatedTextField()
customInput.rightViewMode = .whileEditing
customInput.isSecureTextEntry = true
customInput.keyboardType = .decimalPad

let textInput = AnimatedTextInputFieldConfigurator.configure(with: .generic(textInput: myTextInput))
// use textInput
```
