### ISSUE TITLE
UTTableViewCell

### ISSUE THREAD

**Issue by dkononenko** [jobandtalent/AnimatedTextInput#13]
How add multiline TextInput in UITableViewCell?

Thanks

**Comment by victorBaro** [comment]
Non related to this library. The problem would be exactly the same as using a `UITextView`. 

As a quick answer, I'd recommend you to use `animatedTextInputDidChange` delegate method to check when the height changes for a given width. Once a height change is detected, update the correspondent tableView cell height.

**Comment by dominicwhyte** [comment]
https://medium.com/@ayon/auto-expanding-text-input-ios-c93d0e666cbc
This was helpful for this!
