### ISSUE TITLE
how to use IQKeyboardManager with it?

### ISSUE THREAD

**Issue by Premal-Khetani** [jobandtalent/AnimatedTextInput#14]
Hello i am using IQKeyboardManager also how can i use it with AnimatedTextinput? @victorBaro

**Comment by victorBaro** [comment]
Closing. Out of the scope of this pod. 

---

Sorry I have never used `IQKeyboardManager`. You could try using `AnimatedTextInputFieldConfigurator` with `generic` type and use your own `UITextField` or `UITextView`.
