### ISSUE TITLE
I can't install pod

### ISSUE THREAD

**Issue by RnyG** [jobandtalent/AnimatedTextInput#16]
[!] Unable to find a specification for `AnimatedTextInput (~> 0.3.0)`
[!] Unable to find a specification for `AnimatedTextInput (~> 0.3.2)`
[!] Unable to find a specification for `AnimatedTextInput`

**Comment by victorBaro** [comment]
It is working for me, please try again. If the issue remains, please feel free to reopen it

**Comment by xavierjurado** [comment]
Try running `pod repo update`, chances are you have an outdated repo.
