### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [jobandtalent/AnimatedTextInput#20]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by lfarah** [comment]
Apparently #6 and #19 are fixing this!

**Comment by victorBaro** [comment]
There are 2 PRs opened and we also have our current Swift3 implementation. It is getting out of hands. I will try to update to swift 3 asap.
