### ISSUE TITLE
Placeholder not relocating when textfield clicked

### ISSUE THREAD

**Issue by nitrag** [jobandtalent/AnimatedTextInput#27]
See Gif below. In order to get the placeholder(?) to animate, you must click it? It should trigger when you click the textfield area too.

![out](https://cloud.githubusercontent.com/assets/197010/20544392/daed18fe-b0d7-11e6-94e1-690b16f459c0.gif)

**Comment by bytemines** [comment]
Yes @nitrag  the problem was there, my migration has this weird behaviour.

But is a solution while the other migration is done :)

**Comment by victorBaro** [comment]
Hi guys, the pod has officially been updated to swift 3.

Check version 0.4.0

https://github.com/jobandtalent/AnimatedTextInput/releases/tag/0.4.0

**Comment by nitrag** [comment]
Awesome! Thanks @victorBaro great work and improvements!
