### ISSUE TITLE
Swift 3 delegates broken

### ISSUE THREAD

**Issue by wilferrel** [jobandtalent/AnimatedTextInput#29]
I can't get delegate to call back for : 
`func animatedTextInput(animatedTextInput: AnimatedTextInput, shouldChangeCharactersInRange range: NSRange, replacementString string: String) -> Bool `
and
`    func animatedTextInputDidBeginEditing(animatedTextInput: AnimatedTextInput)`

The only one that seems to work is : 
`    func animatedTextInputDidChange(animatedTextInput: AnimatedTextInput)`

**Comment by wilferrel** [comment]
Issue not apparent in 0.4.0 tag

**Comment by victorBaro** [comment]
Thank you for commenting anyway!
