### ISSUE TITLE
How can I add an icon on the left side?

### ISSUE THREAD

**Issue by D-Link13** [jobandtalent/AnimatedTextInput#31]

**Comment by victorBaro** [comment]
You can't, at least it is not supported by the library.

Can I see a screenshot of what you would like to achieve in both normal and selected states?

**Comment by D-Link13** [comment]
![2017-01-03 22 29 16](https://cloud.githubusercontent.com/assets/1846167/21621984/21672c1e-d204-11e6-8785-6d40738eaff9.png)
Need to achieve this one, no matter about states.

**Comment by victorBaro** [comment]
Sounds like a good addition to the library... Is it possible for you to fork and submit a PR with it? I can do it but it might take a few days.

**Comment by D-Link13** [comment]
Thanks, I have already talked with my employee, we decided to use your version of TextField.
P.S. I think it is not so hard to get the TextField, that i previously needed. If I would have some extra time, I'll make it.

**Comment by victorBaro** [comment]
Thank you, looking forward to it!
