### ISSUE TITLE
Line height?

### ISSUE THREAD

**Issue by vadimvitvickiy** [jobandtalent/AnimatedTextInput#34]
Could i even change this value?

**Comment by victorBaro** [comment]
Unfortunately this is something this control does not currently supports. I have been looking at the code and it is such a quick modification that I will try to find some time during this weekend to add it. 
Thanks for reporting it :)

**Comment by victorBaro** [comment]
The PR is here: https://github.com/jobandtalent/AnimatedTextInput/pull/36

As soon as my colleagues review and approve we will push a new version.
