### ISSUE TITLE
Reset Text Input

### ISSUE THREAD

**Issue by mukulm24** [jobandtalent/AnimatedTextInput#38]
How to reset text input after validation is true.
If we show validation error then later make it blank. The textField shows red line with no placeholder.

**Comment by cesarmtz93** [comment]
@mukulm24  did you manage to solve this?

**Comment by mukulm24** [comment]
How do i refresh the view 
For eg  i entered a wrong value , and then the validation message is seen.
how do i make it normal with placeholder text only/

**Comment by cesarmtz93** [comment]
@mukulm24  there is a clear error function 

```swift
self.textInputs[0].clearError()
```

**Comment by mukulm24** [comment]
Thanks!
