### ISSUE TITLE
Text Alignment

### ISSUE THREAD

**Issue by tarekjradi** [jobandtalent/AnimatedTextInput#41]
Hi,
first of all, congratulations for this project. Do I need know how align the text of textfield at right side, how I can do this?

**Comment by victorBaro** [comment]
Thank you.

[There is a PR that was just approved (v0.5.0)](https://github.com/jobandtalent/AnimatedTextInput/pull/36). It introduced support for attributed strings. This will allow you to create an `NSParagraphStyle` to set right alignment.

Tomorrow I will push the new version to cocoapods, sorry I haven't had time yet (although is in master, you can manually download it)
