### ISSUE TITLE
Over writing on secure text entry

### ISSUE THREAD

**Issue by mukulm24** [jobandtalent/AnimatedTextInput#42]
When the textinput type is of Password type.
Step 1 : Type a password
Step 2 : Click on show/hide button(this shows the password)
Step 3 : Click on show/hide button(this secures the password string )
Step 4 : Type password 
It overwrites over the previous password.
Suppose if user want to check if password is correct or not and start typing again. It doesn't work, user has to type in again.

**Comment by victorBaro** [comment]
Agree. Although don't see it as critical. I believe it is not possible to achieve this with a standard `UITextView` (animatedTextInput secure type uses it under the hood). To achieve it, We would need to store the value in a variable, and set it again between steps 3 and 4 (before the user starts typing).
I need to look into it. 
You are welcome to fork and PR a solution :)
