### ISSUE TITLE
set text in field

### ISSUE THREAD

**Issue by ghost** [jobandtalent/AnimatedTextInput#45]
how can i set the text programmatically
I want something like this
textFieldInput.text = "my added text"

**Comment by victorBaro** [comment]
You can do that. 

In fact, if you download the example project, in `ViewController.swift`, line 42, it wrote exactly that.

You can also check that adding the following line of code in `viewDidLoad()`, it works as expected.

```swift
        textInputs[0].text = "Something"
```
