### ISSUE TITLE
Any clue for me being able to set inputView in AnimatedTextInput? Like UIPickerView or UIDatePicker, thanks in advance

### ISSUE THREAD

**Issue by jorgerebolloj** [jobandtalent/AnimatedTextInput#47]

**Comment by victorBaro** [comment]
Please don't duplicate. Reopen if needed.

Aswer [here](https://github.com/jobandtalent/AnimatedTextInput/issues/39#issuecomment-292612211)

**Comment by jorgerebolloj** [comment]
I agree, sorry about this
