### ISSUE TITLE
Some subviews started to miss.

### ISSUE THREAD

**Issue by morfey911** [jobandtalent/AnimatedTextInput#51]
First of all, great work guys, new release finally fixed constrains warnings in console. But, this update broke counter label (you can simply look this in example). And another issue i just found with views which i tried to put over the AnimatedTextInput view (actually in AnimatedTextInput view stack via IB with auto layout usage), they are missed and i can't find them :). Just try it.

**Comment by hananahmad** [comment]
Hi guys I personally like that control but in old version showCharacterCounterLabel works fine now counter label goes at top left corner auto layout disturbs for multiline please fix that .

**Comment by morfey911** [comment]
As well as adding disclosure view, view goes to wrong place or maybe i do something wrong, please check for this to.

**Comment by victorBaro** [comment]
Hello @morfey911 & @hananahmad 
I will take a look today. Thank you for reporting the issue

**Comment by seecahkhing** [comment]
Any feedback on this issue? Experiencing the same bug as well...

**Comment by victorBaro** [comment]
Hello everyone.

Sorry about this issue. I have it now fixed, will submit a PR + new version asap.

**Comment by victorBaro** [comment]
https://github.com/jobandtalent/AnimatedTextInput/pull/53

**Comment by victorBaro** [comment]
New release 0.5.1 fixing it will come in a few minutes
