### ISSUE TITLE
.Multiline Style Not Using Custom Style

### ISSUE THREAD

**Issue by seecahkhing** [jobandtalent/AnimatedTextInput#54]
The size of the font is always constant during typing and it's not using the Custom AnimatedTextInputStyle. This happens for .multiline style only...

http://imgur.com/a/9TD14

**Comment by jowkame** [comment]
Also it would be great to add some access to content insets parameters in multiline mode.

**Comment by victorBaro** [comment]
@seecahkhing closing -> fixed [here](https://github.com/jobandtalent/AnimatedTextInput/pull/53/commits/2322fd56ef0b48f1b05eddfdf924fd6d7712d236)

@jowkame absolutely. Can you please open a new issue?

**Comment by jowkame** [comment]
@victorBaro sure, added [here](https://github.com/jobandtalent/AnimatedTextInput/issues/56)
