### ISSUE TITLE
Multiline text content alignment/padding improvement

### ISSUE THREAD

**Issue by jowkame** [jobandtalent/AnimatedTextInput#56]
Please add some access to content insets parameters in multiline mode. Something like that:
`animatedInputText.textContainerInset = UIEdgeInsetsMake(10, 10, 10, 10)`

**Comment by victorBaro** [comment]
Thanks for suggesting.

Will be available in next vesion.

https://github.com/jobandtalent/AnimatedTextInput/pull/58
