### ISSUE TITLE
Line thickness

### ISSUE THREAD

**Issue by mariovillamizar** [jobandtalent/AnimatedTextInput#61]
Nice control. Congratulations!

I think that a great improvement could be the option of change the line thickness. Currently it's very thin for my taste.

Another thing that I noticed that when I delete a character on a specific place the cursor return to the last character. I think that it's a better idea to leave the cursor on the same place. Make sense?

**Comment by victorBaro** [comment]
Thank you @mariovillamizar 

I agree with you that having the line width as part of the style would be a great addition. However, it is not a high priority task for us and might not get introduced in the short term. I encourage you to submit a PR if you have the time :)

About the caret, it is a known bug and we will hopefully fix it for the next version. Thank you!
