### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by oxozle** [jobandtalent/AnimatedTextInput#64]
Please add project file and share it to support carthage

**Comment by victorBaro** [comment]
I know Carthage is widely used and we will get to more people if we implement it. However, it is not on our roadmap in short term because we do not use carthage.
You are welcome to submit a PR. It would be a very nice addition :)

**Comment by oxozle** [comment]
Already https://github.com/jobandtalent/AnimatedTextInput/pull/65

**Comment by victorBaro** [comment]
Wow! I was going through all the issues before looking at PRs. 
Thank you!! I will try to find sometime soon to review it

![](https://media0.giphy.com/media/yoJC2GnSClbPOkV0eA/giphy.gif)
