### ISSUE TITLE
Normal Text input Bug

### ISSUE THREAD

**Issue by hananahmad** [jobandtalent/AnimatedTextInput#66]
I have used this library I have find this very useful but I feel there is a minor bug when used the normal text input field and we want to delete some character after selecting the position like we have a text "HelloWorld" in the textfield and I want to delete the "e" from string I have selected the position and deleted "e" but cursor jumps at the end of string always please fix this I will be very thankful .

**Comment by hananahmad** [comment]
Please find some time to look into this issue.

**Comment by adam-konecny** [comment]
I'm also experiencing this bug. Can somebody please fix it? So far I was unable to find a workaround.

**Comment by victorBaro** [comment]
@hananahmad @racak94 We are aware of the bug. We will try to find some time as soon as we can. However, this is an open source project, so we would appreciate if anyone can also take some time and contribute to it by solving the bug. Thanks.
