### ISSUE TITLE
Could your provide Interface Builder???

### ISSUE THREAD

**Issue by farshadmb** [jobandtalent/AnimatedTextInput#69]
Hi Dear 
Could you provide your library with Interface Builder Designer?

Best Regard

**Comment by victorBaro** [comment]
I don't think we will (soon).
I started this project using @IBInspectable and @IBDesignable (so could be configured via IB) but xcode was crashing all the time in big projects.. and we decided to remove them.
Feel free to fork&PR with this addition if you need it, would be nice but not necessary at the moment.
You can still drag a UIView in IB, set its class to `AnimatedTextInput` and modify contents via code (like I did in the Example project).
Thanks.
