### ISSUE TITLE
Phone TextInputType

### ISSUE THREAD

**Issue by PeerLabs** [jobandtalent/AnimatedTextInput#71]
I need to use an AnimatedTextInput that presents a Phone Pad Keyboard Type.
Currently there is just the following:
- Text
- Password
- Numeric
- Selection
- Multiline
- Generic

I need a "Phone" type because .numeric does not allow to have the "+" symbol. The .numeric type has a "." symbol which is not on a phone pad.

Is there a way I can add  this functionality to AnimatedTextInputFieldConfigurator by subclassing it? Im not sure... a bit new to swift.

I would appreciate some advice / pointers... Thanks

**Comment by victorBaro** [comment]
Hello @PeerLabs 
I am planning to update the readme, it is apparently a common problem not knowing how to add your custom types. We only needed 5 types, that is why I decided to create the 6th type, `Generic` with an associated value. The idea is that you create your own `TextInput` and set the type as generic.

You should do something like this:
```swift
//Create your own TextInput. I recommend either using `AnimatedTextField` or `AnimatedTextView`, both are publicly available in the pod.
let myTextField = AnimatedTextField()
myTextField.keyboardType = .phonePad
//configure your textField...
```

After creating and configuring your `TextInput`, you can simply set it like so:
```swift
animatedInput.type = generic(textInput: myTextField)
```

I hope this helps.

**Comment by PeerLabs** [comment]
Hello @victorBaro, 
You sir are a Gentleman and a Scholar!
Thanks!

**Comment by Un3qual** [comment]
Is there a way to get `generic` to accept any subclass of `UITextField`. I'm trying to use [marmelroy/PhoneNumberKit](https://github.com/marmelroy/PhoneNumberKit), but I can't pass a `PhoneNumberTextField` to `.generic`
