### ISSUE TITLE
Issue when set text programmatically

### ISSUE THREAD

**Issue by hoathuongphuoc** [jobandtalent/AnimatedTextInput#72]
Sometime i want to set text by programmatically but text in animatedtextinput i don't see text. I just only saw placeholder above(To). Can you help me fix this bug.
<img width="243" alt="screen shot 2017-08-31 at 9 58 46 am" src="https://user-images.githubusercontent.com/25991485/29904436-056d5f24-8e33-11e7-99a0-5aef7a77039f.png">

**Comment by toftof** [comment]
Have the same issue here. Think this issue only happens when instantiating programatically

**Comment by oxozle** [comment]
You have to:

1. Init `AnimatedTextInput`
2. Set style, type and etc
3. At the end set text (after all init and customisation)

**Comment by annawidera** [comment]
I can confirm that I got rid of this bug by reordering operations: first all the styling, and only then setting the text. 
I have `AnimatedTextInput` as `IBOutlet` connected from Storyboard.

**Comment by jtressle** [comment]
Is there a workaround for this issue?  Since the issue is closed, has this been fixed?  I just tried creating a textField programmatically and I'm getting the same issue as the OP.  The attached code is going in my viewDidLoad() function.

`      let textField = AnimatedTextInput(frame: frame)
        textField.backgroundColor = .lightGray
        
        self.view.addSubview(textField)
        textField.placeHolderText = "Email"`

Thanks in advance!

**Comment by victorBaro** [comment]
It should be working if you specify the correct frame. 
Animated text input uses intrinsic content size to calculate its own height, make sure you give it at least the minimum amount it needs.
I'd also recommend using autolayout, either programatically or using interface builder.
