### ISSUE TITLE
Support for carthage

### ISSUE THREAD

**Issue by toftof** [jobandtalent/AnimatedTextInput#73]
Support for cartage please

**Comment by victorBaro** [comment]
https://github.com/jobandtalent/AnimatedTextInput/pull/65

It was accepted along with others. I need to update the podfile pod version

**Comment by annawidera** [comment]
Hey @victorBaro! I am trying to add AnimatedTextInput via Carthage but unfortunately building the framework fails. Regardless if I specify the exact version or not.
I am using Carthage 0.26.2, Xcode 9.0.1 (also in command line tools). Can somebody check if it's support for Carthage is still working, please? 

What I mean by "it fails" : 
```Build Failed
Task failed with exit code 65:

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/kv/hk4bbcz10xg6fjc0qjblwh9m0000gn/T/carthage-xcodebuild.xTXzfM.log
```

**Comment by ghost** [comment]
@annawidera I update the project to swift 4.0. Now the framework building works fine.
