### ISSUE TITLE
Swift 4 Integration?

### ISSUE THREAD

**Issue by PeerLabs** [jobandtalent/AnimatedTextInput#76]
Wondering about how far is the Swift 4 Integration? ...now that Xcode 9 /iOS 11 has been released!

Regards Abrar

**Comment by victorBaro** [comment]
Hello @PeerLabs 
Sure. I need to allocate some time to review https://github.com/jobandtalent/AnimatedTextInput/pull/75

I will try to do it during this week along with other improvements.

**Comment by SLAppsDev** [comment]
@victorBaro any update on this?

**Comment by alexookah** [comment]
any update?

**Comment by victorBaro** [comment]
Pushing version 0.5.2 with swift4 support @Alexookah
