### ISSUE TITLE
Many errors when downloaded through CocoaPods

### ISSUE THREAD

**Issue by tapizquent** [jobandtalent/AnimatedTextInput#77]
Many errors regarding the Attributed strings in Swift 4

**Comment by hanandev** [comment]
I have used this library in my project and thats very helpful @victorBaro  Please take a look and update this for swift 4 .

**Comment by victorBaro** [comment]
@tapizquent @hanandev sorry guys. Totally understand. I am a bit overload with work at the moment. Will update asap.

**Comment by hanandev** [comment]
@victorBaro Thanks for your prompt reply we will wait for the next release

**Comment by victorBaro** [comment]
Fixing it now. Uploading version 0.5.2
