### ISSUE TITLE
Problem with some letters that are cut by the UIView

### ISSUE THREAD

**Issue by bytemines** [jobandtalent/AnimatedTextInput#8]
How we can solve that?
<img width="368" alt="screen shot 2016-08-10 at 01 27 50" src="https://cloud.githubusercontent.com/assets/16736700/17537097/1888a524-5e9a-11e6-94cf-f128b4f153f1.png">

Thank you in advance.

**Comment by victorBaro** [comment]
Hello @ConradoMateu 
I am uploading version 0.3.1 fixing it.I have noticed that the `CATextLayer` frame needs about 20% more height than the font size in order to render all letters correctly.
Thank you for the catch!

**Comment by D-Link13** [comment]
Same problem on 0.3.2
![2016-10-07 11 24 33](https://cloud.githubusercontent.com/assets/1846167/19183413/cfed3298-8c80-11e6-851e-4e7f5e98182c.png)

**Comment by victorBaro** [comment]
I have just spotted where the problem is. Thank you for pointing it out. Uploading a new version soon.

**Comment by D-Link13** [comment]
Yes, i have seen this in code:
let frameHeightCorrectionFactor: CGFloat = 1.2
,but changing this property unfortunately has no effect =(

**Comment by victorBaro** [comment]
The problem is in `private func styleDidChange()`, the `placeholderLayer.frame` gets a new frame but the `frameHeightCorrectionFactor` it is not applied. I have just fixed. Uploading the changes now.

**Comment by D-Link13** [comment]
Great! Anyway, I have already changed "Login" to "Username", so i fixed it like a true hacker =))

**Comment by victorBaro** [comment]
👏
