### ISSUE TITLE
Swift 4 version

### ISSUE THREAD

**Issue by gwennguihal** [jobandtalent/AnimatedTextInput#81]
Is there a swift 4 version in progress ?

**Comment by alexookah** [comment]
@gwennguihal   check the latest version 0.5.2 its swift 4

**Comment by SLAppsDev** [comment]
@Alexookah I'm still getting errors in the new version  0.5.2 :/ 

`
/Pods/AnimatedTextInput/AnimatedTextInput/Classes/AnimatedTextField.swift:104:75: Cannot convert value of type '[NSAttributedStringKey : Any]?' (aka 'Optional<Dictionary<NSString, Any>>') to expected argument type '[String : Any]?'
`

and many more...

**Comment by alexookah** [comment]
@SLAppsDev do you use swift 4?

**Comment by SLAppsDev** [comment]
@Alexookah ohh no! :S, now that I've updated the pod it won't let me migrate to swift 4 because of the compile erros

**Comment by alexookah** [comment]
remove from pods, migrate to swift 4 . then add again to pods ;)

**Comment by SLAppsDev** [comment]
@Alexookah all set thanks!!.

**Comment by ismaiI1** [comment]
How can i install Swift 4 version? `pod 'AnimatedTextInput', '~> 0.5.2'` mistyped the name or version.
  
Edit :
I found. `pod 'AnimatedTextInput', '0.5.2'`. if it not worked run `pod repo update` before.

**Comment by funct7** [comment]
I think you guys might want to update the README file. The version info about installation was greatly misleading!
