### ISSUE TITLE
Clear button for multiple line input

### ISSUE THREAD

**Issue by AlexisQapa** [jobandtalent/AnimatedTextInput#83]
Hi,

I got an issue with multiline inputs because they don't get the clean button as single lines do.
I think this should be implemented as you expose those properties to multiple line inputs.

One thing to consider while implementing this, is the position of this clear button (top, centered or even bottom). Although I'd be ok with a non customisable one centered.

Did I miss something ?

**Comment by victorBaro** [comment]
No, you didn't miss anything. `AnimatedTextInput` uses 2 different UIKit classes (UITextField or UITextView) underneath depending if it is multiline or not. UITextView does not natively support clear button. 

I agree with you that it should be implemented but it has not been done yet.

However, as a workaround, you can use the function `addDisclosureView` and provide your own button.
