### ISSUE TITLE
Not able to install Pod 

### ISSUE THREAD

**Issue by ghimireprashant** [jobandtalent/AnimatedTextInput#9]
every time i try to install this pod it give me this error
[!] Unable to find a specification for `AnimatedTextInput (~> 0.3.0)`

**Comment by jayminiphonedev** [comment]
Any update for why pod installation is not working ?

**Comment by victorBaro** [comment]
Hello, I have just tried it in a new project and everything works as expected. 
This is my Podfile

```
use_frameworks!

target 'ExampleProject' do
  pod 'AnimatedTextInput', '~> 0.3.0'
end
```

**Comment by ghimireprashant** [comment]
Thank you for reply.. will try it again and will let u know

**Comment by xavierjurado** [comment]
I've also managed to install the pod without issues using the latest stable version of Cocoapods (1.0.1). Have you tried to manually update the main spec repo using `pod repo update` before attempting a new `pod install`? @ghimireprashant @jayminiphonedev

**Comment by victorBaro** [comment]
@ghimireprashant @jayminiphonedev can we close this issue?

**Comment by ghimireprashant** [comment]
thank you @xavierjurado  after i update  pod repo update i was able to install pod. thank you once again @victorBaro  @xavierjurado
