### ISSUE TITLE
After backspace, the letter after capital letter makes keyboard uppercase

### ISSUE THREAD

**Issue by laurenswuyts** [jobandtalent/AnimatedTextInput#96]
<img width="559" alt="screen shot 2018-01-17 at 14 45 38" src="https://user-images.githubusercontent.com/8619460/35045811-59795210-fb95-11e7-9fbb-4988b2aa40ea.png">

Every time when you delete the previous letters and you stop at the first letter which is an uppercase letter than the keyboard goes all uppercase while it is the 2nd letter ..

**Comment by Kirow** [comment]
@laurenswuyts , I also see this issue. Need to Input 3 letters, and then delete two.
However I don't have such issue in my fork. Guess this is related to #90.

You may try to use my fork, or make changes from #90 to your code.

**Comment by victorBaro** [comment]
Hello @laurenswuyts 
I think @Kirow is right. I am sorry I haven't had time to take a look at #90 yet. Will do very soon.
Thank you @kirow for your help.

**Comment by laurenswuyts** [comment]
bump

**Comment by victorBaro** [comment]
Thank you for the bum @laurenswuyts , I am reviewing PRs now and will submit a new version today.

**Comment by victorBaro** [comment]
This issue is fixed in 0.5.3
Pushing it now.
